language: python

notifications:
  email: false

matrix:
  include:
    - os: linux
      python: 2.7
      env: MINICONDA_NAME=Miniconda2-latest-Linux-x86_64.sh
      sudo: required
    - os: osx
      language: generic
      env: MINICONDA_NAME=Miniconda2-latest-MacOSX-x86_64.sh

install:
    - wget http://repo.continuum.io/miniconda/${MINICONDA_NAME} -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - conda env create --file environment_${TRAVIS_OS_NAME}.yml
    - source activate py2_parcels
    - conda install --yes sphinx
    - pip install -e .

script:
    - |
      # Set up display to be able to plot in linux
      if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then
        export DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
        sleep 3;
      fi
    - py.test -v -s tests/
    - |
      # only get examples on linux
      if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then
        parcels_get_examples examples/;
      fi
    - |
      # run linter on linux
      if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then
        flake8 parcels;
        flake8 tests;
      fi
    - |
      # run link checks only on linux
      if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then
        make linkcheck -C docs;
      fi
    - |
      # evaluate example notebooks only on linux
      if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then
        py.test -v -s --nbval-lax examples/;
      fi
